import {clean,freeze,WydgitError} from '../object-model/validation.js';
import {checkContext} from '../seam/context.js';
import {MAXIMA,safeKey} from './schema.js';
import {validate,ensure,fail} from './validate.js';
import {reads,methods} from './bindings.js';
export async function execute(document,{scope,context}) {
 checkContext(context);const program=validate(document),bounds={...MAXIMA};
 for(const key of Object.keys(bounds))bounds[key]=Math.min(bounds[key],context.limits[`sewn${key[0].toUpperCase()+key.slice(1)}`]??bounds[key]);
 let active=true,steps=0,iterations=0,services=0;const deadline=Date.now()+bounds.timeMs,vars=new Map(),refs=new WeakMap();
 const tick=()=>ensure(active&&Date.now()<deadline&&++steps<=bounds.steps,'LIMIT');
 const ref=(value,kind)=>{const token=Object.freeze(Object.create(null));refs.set(token,{value,kind});return token;};
 const data=value=>{let result;try{result=clean(value);}catch{fail('TYPE');}let count=0;const walk=(v,d=0)=>{ensure(d<=bounds.expressionDepth&&++count<=bounds.valueNodes,'LIMIT');if(typeof v==='string')ensure(v.length<=bounds.string,'LIMIT');if(v&&typeof v==='object')Object.values(v).forEach(x=>walk(x,d+1));};walk(result);return freeze(result);};
 const safe=value=>refs.has(value)?value:Array.isArray(value)?(ensure(value.length<=bounds.valueNodes,'LIMIT'),Object.freeze(value.map(safe))):data(value);
 const store=(n,v,declare=false)=>{ensure(declare?!vars.has(n):vars.has(n),'TYPE');if(declare)ensure(vars.size<bounds.variables,'LIMIT');vars.set(n,safe(v));};
 const json=v=>{const visit=x=>{ensure(!refs.has(x),'TYPE');if(x&&typeof x==='object')Object.values(x).forEach(visit);};visit(v);return data(v);};
 const member=(target,key)=>{ensure(safeKey(key)||Number.isSafeInteger(key)&&key>=0,'DENIED');const r=refs.get(target);if(r){ensure(reads[r.kind]?.includes(key),'DENIED');const v=r.value[key];if(key==='Source'||key==='Target')return ref(v,'handle');if(['Query','Form'].includes(key))return ref(v,'map');if(key==='Cookies')return ref(v,r.kind==='RESPONSE'?'cookieWrite':'cookieRead');if(key==='Headers')return ref(v,'headers');return data(v);}
  ensure(target!==null&&typeof target==='object','TYPE');if(Array.isArray(target))ensure(Number.isSafeInteger(key)&&key>=0&&key<target.length,'TYPE');else ensure(Object.hasOwn(target,key),'TYPE');return safe(target[key]);};
 const call=async(target,method,args)=>{tick();const r=refs.get(target),rule=r&&methods[r.kind]?.[method];ensure(rule&&args.length>=rule[0]&&args.length<=rule[1],'DENIED');
  const actual=args.map((v,i)=>{if(r.kind==='handle'&&method==='Move'&&i===0||r.kind==='EVENT'&&method==='Raise'&&i===1){const h=refs.get(v);ensure(h?.kind==='handle','TYPE');return h.value;}return json(v);});
  if(r.kind==='handle'&&['Insert','Replace'].includes(method)){
   const envelope=x=>{ensure(x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).every(k=>['id','type','properties','slots'].includes(k))&&typeof x.id==='string'&&typeof x.type==='string','TYPE');const slots=Object.create(null);for(const [k,children] of Object.entries(x.slots??{})){ensure(Array.isArray(children),'TYPE');slots[k]=children.map(envelope);}return {schema:'wydgit/0.2',id:x.id,prototype:x.type,properties:x.properties??{},slots,provenance:{}};};
   const i=method==='Insert'?2:0;actual[i]=envelope(actual[i]);
  }
  const value=await r.value[method](...actual);tick();if(method==='related'){if(Array.isArray(value))ensure(value.length<=bounds.valueNodes,'LIMIT');return Array.isArray(value)?Object.freeze(value.map(v=>ref(v,'handle'))):value===null?null:ref(value,'handle');}return value===undefined?null:data(value);
 };
 const boolean=v=>{ensure(typeof v==='boolean','TYPE');return v;};
 const expr=async(n,d=0)=>{tick();ensure(d<=bounds.expressionDepth,'LIMIT');const e=x=>expr(x,d+1);
  switch(n.op){case 'array':return data((await argumentsIn(n.items,e)).map(json));case 'object':{const out=Object.create(null);for(const [k,v] of Object.entries(n.fields))out[k]=json(await e(v));return data(out);}case 'literal':return data(n.value);case 'variable':ensure(vars.has(n.name),'TYPE');return vars.get(n.name);case 'context':{const v=scope[n.name];return n.name==='SESSION'?data(v):ref(v,['ME','PAGE'].includes(n.name)?'handle':n.name);}case 'read':return member(await e(n.target),n.key);case 'invoke':return call(await e(n.target),n.method,await argumentsIn(n.args,e));case 'not':return !boolean(await e(n.value));case 'binary':{const a=await e(n.left),op=n.operator;if(op==='AND')return boolean(a)&&boolean(await e(n.right));if(op==='OR')return boolean(a)||boolean(await e(n.right));const b=await e(n.right);ensure(!refs.has(a)&&!refs.has(b),'TYPE');if(op==='='||op==='!='){ensure(a===null||['string','number','boolean'].includes(typeof a),'TYPE');ensure(b===null||['string','number','boolean'].includes(typeof b),'TYPE');return op==='='?a===b:a!==b;}if(['<','<=','>','>='].includes(op)){ensure(typeof a===typeof b&&['string','number'].includes(typeof a),'TYPE');return op==='<'?a<b:op==='<='?a<=b:op==='>'?a>b:a>=b;}if(op==='concat'){ensure(typeof a==='string'&&typeof b==='string','TYPE');return data(a+b);}ensure(typeof a==='number'&&typeof b==='number','TYPE');const v=op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b;ensure(Number.isFinite(v),'TYPE');return v;}}
 };
 const argumentsIn=async(args,e)=>{const values=[];for(const x of args)values.push(await e(x));return values;};
 const body=async(nodes,depth=0)=>{ensure(depth<=bounds.nesting,'LIMIT');for(const n of nodes){tick();switch(n.op){case 'declare':case 'set':store(n.name,await expr(n.value),n.op==='declare');break;case 'if':{const s=await body(boolean(await expr(n.condition))?n.then:n.else??[],depth+1);if(s)return s;break;}case 'forEach':{const items=await expr(n.items);ensure(Array.isArray(items)&&!vars.has(n.name),'TYPE');ensure(vars.size<bounds.variables,'LIMIT');try{for(const item of items){tick();ensure(++iterations<=bounds.iterations,'LIMIT');vars.set(n.name,safe(item));const s=await body(n.body,depth+1);if(s)return s;}}finally{vars.delete(n.name);}break;}case 'call':{const v=await call(await expr(n.target),n.method,await argumentsIn(n.args,expr));if(n.into)store(n.into,v,true);break;}case 'service':{ensure(++services<=bounds.serviceCalls,'LIMIT');const input=json(await expr(n.input));tick();const v=await scope.SERVICES.Call(n.library,n.method,input);tick();if(n.into)store(n.into,data(v),true);break;}case 'return':return {status:'returned',value:json(await expr(n.value))};case 'stop':return {status:'stopped',value:n.value===undefined?null:json(await expr(n.value))};}}return null;};
 let timer;try{return freeze(await Promise.race([body(program.body).then(v=>v??{status:'completed',value:null}),new Promise((_,reject)=>{timer=setTimeout(()=>{active=false;reject(new WydgitError('SEWN.LIMIT','SEWN execution failed'));},bounds.timeMs);})]));}catch(error){throw new WydgitError(error instanceof WydgitError?error.code:'SEWN.EXECUTION_FAILED','SEWN execution failed');}finally{active=false;clearTimeout(timer);}
}
